/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcadiaPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  outputDir: "exports",
  defaultFormat: "pdf",
  authorName: "",
  includeFrontmatter: true,
  includeTOC: false,
  pageSize: "letter",
  fontFamily: "serif"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var ArcadiaPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output directory").setDesc("Folder for exported files (relative to vault root)").addText(
      (text) => text.setPlaceholder("exports").setValue(this.plugin.settings.outputDir).onChange(async (value) => {
        const cleaned = value.trim().replace(/\\/g, "/");
        this.plugin.settings.outputDir = cleaned || "exports";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default export format").setDesc("Format used when exporting via ribbon icon or quick command").addDropdown(
      (dropdown) => dropdown.addOption("pdf", "PDF").addOption("html", "HTML").setValue(this.plugin.settings.defaultFormat).onChange(async (value) => {
        this.plugin.settings.defaultFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Author name").setDesc("Used in document metadata and header").addText(
      (text) => text.setPlaceholder("Your name").setValue(this.plugin.settings.authorName).onChange(async (value) => {
        this.plugin.settings.authorName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include frontmatter header").setDesc("Show title, author, and date at the top of exported documents").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeFrontmatter).onChange(async (value) => {
        this.plugin.settings.includeFrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include table of contents").setDesc("Generate a table of contents from headings").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeTOC).onChange(async (value) => {
        this.plugin.settings.includeTOC = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Page size").setDesc("Paper size for PDF export").addDropdown(
      (dropdown) => dropdown.addOption("letter", "Letter (8.5 x 11 in)").addOption("a4", "A4 (210 x 297 mm)").setValue(this.plugin.settings.pageSize).onChange(async (value) => {
        this.plugin.settings.pageSize = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Font family").setDesc("Primary font for exported documents").addDropdown(
      (dropdown) => dropdown.addOption("serif", "Serif (Georgia)").addOption("sans", "Sans-serif (system UI)").addOption("mono", "Monospace (Consolas)").setValue(this.plugin.settings.fontFamily).onChange(async (value) => {
        this.plugin.settings.fontFamily = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/export-modal.ts
var import_obsidian5 = require("obsidian");

// src/html-exporter.ts
var import_obsidian3 = require("obsidian");

// src/markdown-processor.ts
var import_obsidian2 = require("obsidian");

// src/templates.ts
var FONT_STACKS = {
  serif: 'Georgia, "Times New Roman", Times, serif',
  sans: 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  mono: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace'
};
function getDocumentCSS(settings) {
  const fontStack = FONT_STACKS[settings.fontFamily] || FONT_STACKS.serif;
  const pageSize = settings.pageSize === "a4" ? "A4" : "letter";
  return `
/* Arcadia Publisher Document Styles */
@page {
	size: ${pageSize};
	margin: 1in;
}

@media print {
	body {
		margin: 0;
		padding: 0;
	}
	.arcadia-doc-toc {
		page-break-after: always;
	}
	h1, h2, h3, h4, h5, h6 {
		page-break-after: avoid;
	}
	pre, table, figure, blockquote {
		page-break-inside: avoid;
	}
	img {
		max-width: 100%;
		page-break-inside: avoid;
	}
}

* {
	box-sizing: border-box;
}

html {
	font-size: 16px;
}

body {
	font-family: ${fontStack};
	line-height: 1.7;
	color: #1a1a1a;
	max-width: 42em;
	margin: 0 auto;
	padding: 2rem 1rem;
	background: #fff;
}

/* Document Header */
.arcadia-doc-header {
	text-align: center;
	margin-bottom: 2.5rem;
	padding-bottom: 1.5rem;
	border-bottom: 1px solid #ddd;
}

.arcadia-doc-header h1 {
	font-size: 2rem;
	margin: 0 0 0.5rem 0;
	border-bottom: none;
	padding-bottom: 0;
}

.arcadia-doc-header .arcadia-doc-author {
	font-size: 1.1rem;
	color: #555;
	margin: 0.25rem 0;
}

.arcadia-doc-header .arcadia-doc-date {
	font-size: 0.95rem;
	color: #777;
	margin: 0.25rem 0;
}

/* Table of Contents */
.arcadia-doc-toc {
	margin: 1.5rem 0 2.5rem 0;
	padding: 1.25rem 1.5rem;
	background: #f8f8f8;
	border: 1px solid #e0e0e0;
	border-radius: 4px;
}

.arcadia-doc-toc h2 {
	font-size: 1.2rem;
	margin: 0 0 0.75rem 0;
	border-bottom: none;
	padding-bottom: 0;
}

.arcadia-doc-toc ul {
	list-style: none;
	padding-left: 0;
	margin: 0;
}

.arcadia-doc-toc ul ul {
	padding-left: 1.25rem;
}

.arcadia-doc-toc li {
	margin: 0.3rem 0;
}

.arcadia-doc-toc a {
	color: #333;
	text-decoration: none;
}

.arcadia-doc-toc a:hover {
	text-decoration: underline;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
	margin-top: 1.5em;
	margin-bottom: 0.5em;
	font-weight: 600;
	line-height: 1.3;
}

h1 {
	font-size: 1.8rem;
	border-bottom: 1px solid #e0e0e0;
	padding-bottom: 0.3rem;
}

h2 {
	font-size: 1.5rem;
	border-bottom: 1px solid #eee;
	padding-bottom: 0.2rem;
}

h3 { font-size: 1.25rem; }
h4 { font-size: 1.1rem; }
h5 { font-size: 1rem; }
h6 { font-size: 0.95rem; color: #555; }

/* Paragraphs */
p {
	margin: 0.75em 0;
}

/* Links */
a {
	color: #2563eb;
	text-decoration: none;
}

a:hover {
	text-decoration: underline;
}

/* Lists */
ul, ol {
	padding-left: 1.5em;
	margin: 0.75em 0;
}

li {
	margin: 0.25em 0;
}

li > ul, li > ol {
	margin: 0.15em 0;
}

/* Blockquotes */
blockquote {
	margin: 1em 0;
	padding: 0.5em 1em;
	border-left: 4px solid #d0d0d0;
	background: #f9f9f9;
	color: #444;
}

blockquote p {
	margin: 0.4em 0;
}

blockquote blockquote {
	border-left-color: #bbb;
}

/* Code */
code {
	font-family: ${FONT_STACKS.mono};
	font-size: 0.9em;
	background: #f3f3f3;
	padding: 0.15em 0.35em;
	border-radius: 3px;
}

pre {
	margin: 1em 0;
	padding: 1em;
	background: #f5f5f5;
	border: 1px solid #e0e0e0;
	border-radius: 4px;
	overflow-x: auto;
	line-height: 1.5;
}

pre code {
	background: none;
	padding: 0;
	border-radius: 0;
	font-size: 0.85em;
}

/* Tables */
table {
	width: 100%;
	border-collapse: collapse;
	margin: 1em 0;
	font-size: 0.95em;
}

thead {
	background: #f5f5f5;
}

th, td {
	border: 1px solid #ddd;
	padding: 0.5em 0.75em;
	text-align: left;
}

th {
	font-weight: 600;
}

tr:nth-child(even) {
	background: #fafafa;
}

/* Horizontal Rule */
hr {
	border: none;
	border-top: 1px solid #ddd;
	margin: 2em 0;
}

/* Images */
img {
	max-width: 100%;
	height: auto;
	display: block;
	margin: 1em auto;
}

/* Footnotes */
.footnotes {
	margin-top: 2rem;
	padding-top: 1rem;
	border-top: 1px solid #ddd;
	font-size: 0.9em;
}

.footnotes ol {
	padding-left: 1.25em;
}

.footnotes li {
	margin: 0.5em 0;
}

/* Task Lists */
ul.contains-task-list {
	list-style: none;
	padding-left: 0.5em;
}

.task-list-item {
	display: flex;
	align-items: baseline;
	gap: 0.5em;
}

.task-list-item input[type="checkbox"] {
	margin: 0;
}

/* Callouts (simplified for export) */
.callout {
	margin: 1em 0;
	padding: 0.75em 1em;
	border-left: 4px solid #5090d0;
	background: #f0f5fa;
	border-radius: 0 4px 4px 0;
}

.callout-title {
	font-weight: 600;
	margin-bottom: 0.25em;
}

/* Definition Lists */
dt {
	font-weight: 600;
	margin-top: 0.75em;
}

dd {
	margin-left: 1.5em;
	margin-bottom: 0.5em;
}

/* Math (basic styling if KaTeX renders) */
.math {
	overflow-x: auto;
}

/* Emphasis */
strong { font-weight: 700; }
em { font-style: italic; }
mark {
	background: #fff3b0;
	padding: 0.1em 0.2em;
}

del {
	text-decoration: line-through;
	color: #888;
}
`.trim();
}
function getHTMLTemplate(title, css, bodyContent) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="generator" content="Arcadia Publisher">
	<title>${escapeHTML(title)}</title>
	<style>
${css}
	</style>
</head>
<body>
${bodyContent}
</body>
</html>`;
}
function escapeHTML(str) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}

// src/markdown-processor.ts
var IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "svg", "webp", "bmp", "avif"];
var MarkdownProcessor = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async process(file) {
    const content = await this.app.vault.read(file);
    const { frontmatter, body } = this.splitFrontmatter(content);
    const metadata = this.extractMetadata(frontmatter, file);
    const container = createDiv();
    const component = new import_obsidian2.Component();
    component.load();
    try {
      await import_obsidian2.MarkdownRenderer.render(
        this.app,
        body,
        container,
        file.path,
        component
      );
      await this.embedImages(container, file);
      const tocEntries = this.assignHeadingIDs(container);
      const parts = [];
      if (this.settings.includeFrontmatter) {
        parts.push(this.buildDocumentHeader(metadata));
      }
      if (this.settings.includeTOC && tocEntries.length > 0) {
        parts.push(this.buildTOC(tocEntries));
      }
      parts.push(`<div class="arcadia-doc-content">${container.innerHTML}</div>`);
      return parts.join("\n");
    } finally {
      component.unload();
    }
  }
  getMetadata(content, file) {
    const { frontmatter } = this.splitFrontmatter(content);
    return this.extractMetadata(frontmatter, file);
  }
  splitFrontmatter(content) {
    const fmRegex = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
    const match = content.match(fmRegex);
    if (!match) {
      return { frontmatter: {}, body: content };
    }
    const fmRaw = match[1];
    const body = content.slice(match[0].length);
    const frontmatter = this.parseSimpleYAML(fmRaw);
    return { frontmatter, body };
  }
  parseSimpleYAML(yaml) {
    const result = {};
    const lines = yaml.split(/\r?\n/);
    let currentKey = "";
    let arrayValues = null;
    for (const line of lines) {
      if (line.match(/^\s+-\s+/) && currentKey) {
        const value = line.replace(/^\s+-\s+/, "").trim();
        if (arrayValues === null) {
          arrayValues = [];
        }
        arrayValues.push(value);
        result[currentKey] = arrayValues;
        continue;
      }
      const kvMatch = line.match(/^([a-zA-Z0-9_-]+)\s*:\s*(.*)/);
      if (kvMatch) {
        arrayValues = null;
        currentKey = kvMatch[1];
        const value = kvMatch[2].trim();
        if (value === "") {
          result[currentKey] = "";
        } else {
          result[currentKey] = value.replace(/^["']|["']$/g, "");
        }
      }
    }
    return result;
  }
  extractMetadata(frontmatter, file) {
    const title = frontmatter.title || file.basename;
    const author = frontmatter.author || this.settings.authorName || "";
    const date = frontmatter.date || this.formatDate(file.stat.mtime);
    const description = frontmatter.description || void 0;
    const tags = Array.isArray(frontmatter.tags) ? frontmatter.tags : void 0;
    return { title, author, date, description, tags };
  }
  formatDate(timestamp) {
    const d = new Date(timestamp);
    const months = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ];
    return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}`;
  }
  /**
   * Embed local images as base64 data URIs. Handles both markdown-style
   * images (rendered as <img>) and wiki-style embeds (![[image.png]]),
   * which the renderer leaves as internal-embed spans when the container
   * is not attached to the live DOM.
   */
  async embedImages(container, contextFile) {
    const images = Array.from(container.querySelectorAll("img"));
    for (const img of images) {
      const src = img.getAttribute("src");
      if (!src || src.startsWith("data:"))
        continue;
      if (src.startsWith("http://") || src.startsWith("https://"))
        continue;
      const dataUri = await this.imageToBase64(src, contextFile);
      if (dataUri) {
        img.setAttribute("src", dataUri);
      }
    }
    const embeds = Array.from(
      container.querySelectorAll("span.internal-embed")
    );
    for (const embed of embeds) {
      if (embed.querySelector("img"))
        continue;
      const src = embed.getAttribute("src");
      if (!src)
        continue;
      const dataUri = await this.imageToBase64(src, contextFile);
      if (!dataUri)
        continue;
      const img = createEl("img", {
        attr: {
          src: dataUri,
          alt: embed.getAttribute("alt") || src
        }
      });
      embed.replaceWith(img);
    }
  }
  async imageToBase64(src, contextFile) {
    const imageFile = this.resolveImageFile(src, contextFile);
    if (!imageFile)
      return null;
    const ext = imageFile.extension.toLowerCase();
    if (!IMAGE_EXTENSIONS.includes(ext))
      return null;
    try {
      const arrayBuffer = await this.app.vault.readBinary(imageFile);
      const bytes = new Uint8Array(arrayBuffer);
      let binary = "";
      const chunkSize = 32768;
      for (let i = 0; i < bytes.length; i += chunkSize) {
        const chunk = bytes.subarray(i, i + chunkSize);
        binary += String.fromCharCode(...Array.from(chunk));
      }
      const base64 = window.btoa(binary);
      const mimeType = this.getMimeType(ext);
      return `data:${mimeType};base64,${base64}`;
    } catch (e) {
      return null;
    }
  }
  resolveImageFile(src, contextFile) {
    if (src.startsWith("app://")) {
      const rel = this.vaultPathFromResourceUrl(src);
      if (!rel)
        return null;
      const file = this.app.vault.getAbstractFileByPath(rel);
      return file instanceof import_obsidian2.TFile ? file : null;
    }
    let decoded = src;
    try {
      decoded = decodeURIComponent(src);
    } catch (e) {
    }
    const dest = this.app.metadataCache.getFirstLinkpathDest(
      decoded,
      contextFile.path
    );
    if (dest)
      return dest;
    const byPath = this.app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(decoded));
    return byPath instanceof import_obsidian2.TFile ? byPath : null;
  }
  vaultPathFromResourceUrl(src) {
    try {
      const url = new URL(src);
      let full = decodeURIComponent(url.pathname).replace(/\\/g, "/");
      if (full.startsWith("/"))
        full = full.slice(1);
      const adapter = this.app.vault.adapter;
      if (adapter instanceof import_obsidian2.FileSystemAdapter) {
        const base = adapter.getBasePath().replace(/\\/g, "/").replace(/\/$/, "");
        if (full.toLowerCase().startsWith(`${base.toLowerCase()}/`)) {
          return (0, import_obsidian2.normalizePath)(full.slice(base.length + 1));
        }
      }
      return null;
    } catch (e) {
      return null;
    }
  }
  getMimeType(ext) {
    const types = {
      png: "image/png",
      jpg: "image/jpeg",
      jpeg: "image/jpeg",
      gif: "image/gif",
      svg: "image/svg+xml",
      webp: "image/webp",
      bmp: "image/bmp",
      avif: "image/avif"
    };
    return types[ext] || "image/png";
  }
  buildDocumentHeader(metadata) {
    const parts = [];
    parts.push('<div class="arcadia-doc-header">');
    parts.push(`  <h1>${escapeHTML(metadata.title)}</h1>`);
    if (metadata.author) {
      parts.push(`  <p class="arcadia-doc-author">${escapeHTML(metadata.author)}</p>`);
    }
    if (metadata.date) {
      parts.push(`  <p class="arcadia-doc-date">${escapeHTML(metadata.date)}</p>`);
    }
    parts.push("</div>");
    return parts.join("\n");
  }
  /**
   * Assign an id to every heading that lacks one and collect TOC entries.
   * Entries always reference the actual id on the heading, so TOC links
   * cannot drift out of sync with their targets.
   */
  assignHeadingIDs(container) {
    const entries = [];
    const headings = Array.from(
      container.querySelectorAll("h1, h2, h3, h4, h5, h6")
    );
    let counter = 0;
    for (const heading of headings) {
      const level = parseInt(heading.tagName.slice(1), 10);
      const text = (heading.textContent || "").trim();
      let id = heading.getAttribute("id");
      if (!id) {
        id = `heading-${counter++}`;
        heading.setAttribute("id", id);
      }
      entries.push({ level, text, id });
    }
    return entries;
  }
  buildTOC(entries) {
    const minLevel = Math.min(...entries.map((e) => e.level));
    const parts = [];
    parts.push('<div class="arcadia-doc-toc">');
    parts.push("  <h2>Table of contents</h2>");
    let html = "";
    let prev = 0;
    for (const entry of entries) {
      const level = Math.min(entry.level - minLevel + 1, prev + 1);
      if (prev === 0) {
        html += "<ul>";
      } else if (level > prev) {
        html += "<ul>";
      } else {
        html += "</li>";
        for (let i = level; i < prev; i++) {
          html += "</ul></li>";
        }
      }
      html += `<li><a href="#${entry.id}">${escapeHTML(entry.text)}</a>`;
      prev = level;
    }
    html += "</li>";
    for (let i = 1; i < prev; i++) {
      html += "</ul></li>";
    }
    html += "</ul>";
    parts.push(`  ${html}`);
    parts.push("</div>");
    return parts.join("\n");
  }
};

// src/html-exporter.ts
var HTMLExporter = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async export(file) {
    try {
      const processor = new MarkdownProcessor(this.app, this.settings);
      const bodyContent = await processor.process(file);
      const css = getDocumentCSS(this.settings);
      const rawContent = await this.app.vault.read(file);
      const metadata = processor.getMetadata(rawContent, file);
      const title = metadata.title;
      const fullHTML = getHTMLTemplate(title, css, bodyContent);
      const outputDir = resolveOutputDir(this.settings.outputDir);
      await ensureDirectory(this.app, outputDir);
      const outputName = `${file.basename}.html`;
      const outputPath = outputDir ? `${outputDir}/${outputName}` : outputName;
      const existingFile = this.app.vault.getAbstractFileByPath(outputPath);
      if (existingFile instanceof import_obsidian3.TFile) {
        await this.app.vault.modify(existingFile, fullHTML);
      } else {
        await this.app.vault.create(outputPath, fullHTML);
      }
      return {
        success: true,
        outputPath
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        success: false,
        error: `HTML export failed: ${message}`
      };
    }
  }
};
function resolveOutputDir(outputDir) {
  const cleaned = (outputDir || "").trim().replace(/\\/g, "/");
  if (!cleaned || cleaned === "/" || cleaned === ".")
    return "exports";
  const normalized = (0, import_obsidian3.normalizePath)(cleaned);
  return normalized === "/" ? "" : normalized;
}
async function ensureDirectory(app, path) {
  if (!path)
    return;
  const parts = path.split("/").filter((p) => p.length > 0);
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    const existing = app.vault.getAbstractFileByPath(current);
    if (!existing) {
      try {
        await app.vault.createFolder(current);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (!msg.toLowerCase().includes("exist")) {
          throw err;
        }
      }
    }
  }
}

// src/pdf-exporter.ts
var import_obsidian4 = require("obsidian");
var import_url = require("url");
var PDF_RENDER_TIMEOUT_MS = 45e3;
var PDFExporter = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async export(file) {
    try {
      const processor = new MarkdownProcessor(this.app, this.settings);
      const bodyContent = await processor.process(file);
      const css = getDocumentCSS(this.settings);
      const rawContent = await this.app.vault.read(file);
      const metadata = processor.getMetadata(rawContent, file);
      const title = metadata.title;
      const fullHTML = getHTMLTemplate(title, css, bodyContent);
      const pageSizeName = this.settings.pageSize === "a4" ? "A4" : "Letter";
      const pdfBuffer = await this.renderToPDF(fullHTML, pageSizeName);
      const outputDir = resolveOutputDir(this.settings.outputDir);
      await ensureDirectory(this.app, outputDir);
      const outputName = `${file.basename}.pdf`;
      const outputPath = outputDir ? `${outputDir}/${outputName}` : outputName;
      const existingFile = this.app.vault.getAbstractFileByPath(outputPath);
      if (existingFile instanceof import_obsidian4.TFile) {
        await this.app.vault.modifyBinary(existingFile, pdfBuffer);
      } else {
        await this.app.vault.createBinary(outputPath, pdfBuffer);
      }
      return {
        success: true,
        outputPath
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        success: false,
        error: `PDF export failed: ${message}`
      };
    }
  }
  async renderToPDF(html, pageSizeName) {
    var _a;
    const electron = require("electron");
    const BrowserWindow = (_a = electron.remote) == null ? void 0 : _a.BrowserWindow;
    if (!BrowserWindow) {
      throw new Error("PDF rendering is only available in the Obsidian desktop app.");
    }
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian4.FileSystemAdapter)) {
      throw new Error("PDF export requires a vault stored on the local file system.");
    }
    const tmpPath = (0, import_obsidian4.normalizePath)(
      `${this.app.vault.configDir}/arcadia-publisher-print.tmp.html`
    );
    await adapter.write(tmpPath, html);
    const fileUrl = (0, import_url.pathToFileURL)(adapter.getFullPath(tmpPath)).toString();
    try {
      return await new Promise((resolve, reject) => {
        const win = new BrowserWindow({
          show: false,
          width: 800,
          height: 600,
          webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            sandbox: true
          }
        });
        let settled = false;
        const finish = (complete) => {
          if (settled)
            return;
          settled = true;
          activeWindow.clearTimeout(timeoutId);
          try {
            win.destroy();
          } catch (e) {
          }
          complete();
        };
        const timeoutId = activeWindow.setTimeout(() => {
          finish(
            () => reject(
              new Error(
                `PDF rendering timed out after ${PDF_RENDER_TIMEOUT_MS / 1e3} seconds.`
              )
            )
          );
        }, PDF_RENDER_TIMEOUT_MS);
        win.webContents.on("did-finish-load", () => {
          activeWindow.setTimeout(() => {
            win.webContents.printToPDF({
              pageSize: pageSizeName,
              printBackground: true,
              margins: { marginType: "none" },
              preferCSSPageSize: true
            }).then((data) => {
              const arrayBuffer = new ArrayBuffer(data.byteLength);
              new Uint8Array(arrayBuffer).set(data);
              finish(() => resolve(arrayBuffer));
            }).catch((err) => {
              finish(() => reject(err));
            });
          }, 250);
        });
        win.webContents.on(
          "did-fail-load",
          (_event, errorCode, errorDescription) => {
            finish(
              () => reject(
                new Error(
                  `Failed to load content for PDF rendering: ${errorDescription} (${errorCode})`
                )
              )
            );
          }
        );
        win.loadURL(fileUrl);
      });
    } finally {
      try {
        await adapter.remove(tmpPath);
      } catch (e) {
      }
    }
  }
};

// src/export-modal.ts
var ExportModal = class extends import_obsidian5.Modal {
  constructor(app, file, settings) {
    super(app);
    this.exporting = false;
    this.file = file;
    this.settings = settings;
    this.selectedFormat = settings.defaultFormat;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("arcadia-publisher-modal");
    this.titleEl.setText("Export note");
    contentEl.createEl("p", {
      text: this.file.basename,
      cls: "arcadia-publisher-modal-filename"
    });
    new import_obsidian5.Setting(contentEl).setName("Export format").addDropdown(
      (dropdown) => dropdown.addOption("pdf", "PDF").addOption("html", "HTML").setValue(this.selectedFormat).onChange((value) => {
        this.selectedFormat = value;
      })
    );
    const summaryEl = contentEl.createDiv({
      cls: "arcadia-publisher-modal-summary"
    });
    summaryEl.createEl("p", {
      text: `Output: ${this.settings.outputDir}/`
    });
    summaryEl.createEl("p", {
      text: `Page size: ${this.settings.pageSize === "a4" ? "A4" : "Letter"}`
    });
    summaryEl.createEl("p", {
      text: `Font: ${this.settings.fontFamily}`
    });
    summaryEl.createEl("p", {
      text: `Table of contents: ${this.settings.includeTOC ? "yes" : "no"}`
    });
    const progressEl = contentEl.createDiv({
      cls: "arcadia-publisher-modal-progress"
    });
    progressEl.addClass("arcadia-publisher-hidden");
    const buttonContainer = contentEl.createDiv({
      cls: "arcadia-publisher-modal-buttons"
    });
    const exportBtn = buttonContainer.createEl("button", {
      text: "Export",
      cls: "mod-cta"
    });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "Cancel"
    });
    exportBtn.addEventListener("click", () => {
      void (async () => {
        if (this.exporting)
          return;
        this.exporting = true;
        exportBtn.disabled = true;
        exportBtn.textContent = "Exporting...";
        progressEl.removeClass("arcadia-publisher-hidden");
        progressEl.textContent = `Exporting to ${this.selectedFormat.toUpperCase()}...`;
        try {
          const result = await this.runExport();
          if (result.success) {
            new import_obsidian5.Notice(
              `Exported to ${result.outputPath}`,
              5e3
            );
          } else {
            new import_obsidian5.Notice(
              `Export failed: ${result.error}`,
              8e3
            );
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian5.Notice(`Export error: ${msg}`, 8e3);
        }
        this.close();
      })();
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async runExport() {
    if (this.selectedFormat === "html") {
      const exporter = new HTMLExporter(this.app, this.settings);
      return exporter.export(this.file);
    } else {
      const exporter = new PDFExporter(this.app, this.settings);
      return exporter.export(this.file);
    }
  }
};

// src/main.ts
var ArcadiaPublisherPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ArcadiaPublisherSettingTab(this.app, this));
    this.addCommand({
      id: "export-to-pdf",
      name: "Export current note to PDF",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md")
          return false;
        if (!checking) {
          void this.exportFile(file, "pdf");
        }
        return true;
      }
    });
    this.addCommand({
      id: "export-to-html",
      name: "Export current note to HTML",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md")
          return false;
        if (!checking) {
          void this.exportFile(file, "html");
        }
        return true;
      }
    });
    this.addCommand({
      id: "export-current-note",
      name: "Export current note...",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension !== "md")
          return false;
        if (!checking) {
          new ExportModal(this.app, file, this.settings).open();
        }
        return true;
      }
    });
    this.addRibbonIcon("file-output", "Export note", () => {
      const file = this.app.workspace.getActiveFile();
      if (!file || file.extension !== "md") {
        new import_obsidian6.Notice("Open a Markdown note to export it.");
        return;
      }
      new ExportModal(this.app, file, this.settings).open();
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async exportFile(file, format) {
    new import_obsidian6.Notice(`Exporting ${file.basename} to ${format.toUpperCase()}...`);
    try {
      let result;
      if (format === "html") {
        const exporter = new HTMLExporter(this.app, this.settings);
        result = await exporter.export(file);
      } else {
        const exporter = new PDFExporter(this.app, this.settings);
        result = await exporter.export(file);
      }
      if (result.success) {
        new import_obsidian6.Notice(`Exported: ${result.outputPath}`, 5e3);
      } else {
        new import_obsidian6.Notice(`Export failed: ${result.error}`, 8e3);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      new import_obsidian6.Notice(`Export error: ${msg}`, 8e3);
    }
  }
};
